In [1]:
print("hello hello")

hello hello


In [3]:
import numpy as np
mylist =[1,2,3]
print (mylist)

[1, 2, 3]


In [4]:
type(mylist)

list

In [6]:
arr=np.array(mylist)

In [7]:
type(arr)

numpy.ndarray

In [9]:
arr

array([1, 2, 3])

In [12]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
np.zeros(shape=(5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.zeros(shape=(5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
type(0)

int

In [19]:
type(0.0)

float

In [20]:
type(0.)

float

In [21]:
np.ones(shape=(4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
np.random.seed(101)
arr= np.random.randint(0,100,10)
print (arr)

[95 11 81 70 63 87 75  9 77 40]


In [27]:
arr2= np.random.randint(0,100,10)

In [28]:
arr2

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [29]:
arr.max()

95

In [31]:
arr.argmax()

0

In [32]:
arr.min()

9

In [34]:
arr.argmin()

7

In [35]:
arr.mean()

60.8

In [37]:
arr.shape

(10,)

In [38]:
arr.reshape(2,5)

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [39]:
arr.reshape(5,5)

ValueError: cannot reshape array of size 10 into shape (5,5)

In [40]:
arr.reshape(5,2)

array([[95, 11],
       [81, 70],
       [63, 87],
       [75,  9],
       [77, 40]])

In [42]:
mat = np.arange(0,100).reshape(10,10)

In [43]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [45]:
row = 0
col = 1

In [46]:
mat[row,col]

1

In [47]:
mat[2,7]

27

In [48]:
mat[:,7]

array([ 7, 17, 27, 37, 47, 57, 67, 77, 87, 97])

In [51]:
mat[0:3,0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [52]:
mat[0:3,0:4]

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

In [53]:
mat[0:3,0:4]=0

In [54]:
mat

array([[ 0,  0,  0,  0,  4,  5,  6,  7,  8,  9],
       [ 0,  0,  0,  0, 14, 15, 16, 17, 18, 19],
       [ 0,  0,  0,  0, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [55]:
mynewmat=mat.copy()

In [56]:
mynewmat

array([[ 0,  0,  0,  0,  4,  5,  6,  7,  8,  9],
       [ 0,  0,  0,  0, 14, 15, 16, 17, 18, 19],
       [ 0,  0,  0,  0, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [57]:
mynewmat[0:3,0:6]=999

In [58]:
mynewmat

array([[999, 999, 999, 999, 999, 999,   6,   7,   8,   9],
       [999, 999, 999, 999, 999, 999,  16,  17,  18,  19],
       [999, 999, 999, 999, 999, 999,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]])